id: I4206E91B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:06:38+00:00'
last_modified: '2022-06-09T05:06:23.036421+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17459
  title: གཏེར་ཆོས། གཏེར་སྟོན་རིན་ཆེན་གླིང་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C1C1:
      image_group_id: I4PD529
      title: ''
      total_pages: 528
      order: 1
      base_file: C1C1.txt
    E129:
      image_group_id: I4PD530
      title: ''
      total_pages: 408
      order: 2
      base_file: E129.txt
    '4109':
      image_group_id: I4PD531
      title: ''
      total_pages: 1110
      order: 3
      base_file: 4109.txt
    AAA4:
      image_group_id: I4PD532
      title: ''
      total_pages: 320
      order: 4
      base_file: AAA4.txt
    D6E2:
      image_group_id: I4PD533
      title: ''
      total_pages: 246
      order: 5
      base_file: D6E2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
