id: I4206E91B
legacy_id: P008187
ocr_import_info:
  bdrc_scan_id: W2PD17459
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T15:04:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T10:16:16.487276+00:00'
last_modified: 2022-09-03 18:17:13.631665
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD17459
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2PD17459
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏེར་ཆོས། གཏེར་སྟོན་རིན་ཆེན་གླིང་པ།
  author: གཏེར་སྟོན་རིན་ཆེན་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6649838861455821
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I4PD529:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD529
      total_pages: 528
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD529.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.734283947041131
    legacy_id: v001
  I4PD533:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD533
      total_pages: 246
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4PD533.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6859796185698748
    legacy_id: v005
  I4PD532:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD532
      total_pages: 320
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4PD532.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.604107183613937
    legacy_id: v004
  I4PD530:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD530
      total_pages: 408
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD530.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7375026703067606
    legacy_id: v002
  I4PD531:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD531
      total_pages: 1110
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD531.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6073760366240679
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
